/*
** EPITECH PROJECT, 2024
** My_paint
** File description:
** texture
*/

#ifndef TEXTURE_H_
    #define TEXTURE_H_

typedef enum e_texture {
    DRAWING = 0,
    BACKGROUND_TEXTURE,
    FILE_EDITOR_TEXTURE,
    NEW_FILE_TEXTURE,
    OPEN_FILE_TEXTURE,
    SAVE_FILE_TEXTURE,
    TOOL_MENU_TEXTURE,
    BRUSH_TEXTURE,
    DROPPER_TEXTURE,
    ERASER_TEXTURE,
    PENCIL_TEXTURE,
    HELP_TEXTURE,
    CIRCLE_TEXTURE,
    SQUARE_TEXTURE,
    TINY_SIZE_TEXTURE,
    SMALL_SIZE_TEXTURE,
    MEDIUM_SIZE_TEXTURE,
    BIG_SIZE_TEXTURE,
    BIN_TEXTURE,
    FLIP_VERTICAL_TEXTURE,
    FLIP_HORIZONTAL_TEXTURE,
    LOGIN_TEXTURE,
    TUTORIAL_TEXTURE,
    BUCKET_TEXTURE,
    HAMMER_TEXTURE,
    SIZE
} e_texture;

#endif /* !TEXTURE_H_ */
